# Generated by Django 3.1.7 on 2023-03-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeATest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(auto_now_add=True)),
                ('time_left', models.DurationField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(auto_now_add=True)),
                ('time_left', models.DurationField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=1)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('exam_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.examdetail')),
                ('take_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.takeatest')),
            ],
        ),
        migrations.CreateModel(
            name='CompletePractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('exam_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.examdetail')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.practice')),
            ],
        ),
    ]
