# Generated by Django 3.1.7 on 2023-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_completepractice_completetest_examdetail_practice_takeatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='quizz/images/default.jpeg', upload_to='quizz/images'),
        ),
    ]
