# Generated by Django 3.1.7 on 2023-03-11 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0004_auto_20230305_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DurationField()),
                ('pass_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, upload_to='media/')),
                ('exam_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.exampart')),
            ],
        ),
        migrations.CreateModel(
            name='GroupQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePartHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DurationField()),
                ('pass_score', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('time_left', models.DurationField()),
                ('practice_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.practicehistory')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('correct', models.CharField(max_length=1)),
                ('group_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.groupquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('correct', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=1)),
                ('group_question_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.groupquestionhistory')),
            ],
        ),
        migrations.RemoveField(
            model_name='completetest',
            name='exam_detail',
        ),
        migrations.RemoveField(
            model_name='completetest',
            name='take_test',
        ),
        migrations.RemoveField(
            model_name='examdetail',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takeatest',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='takeatest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takeatest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='media/default.jpeg', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='CompletePractice',
        ),
        migrations.DeleteModel(
            name='CompleteTest',
        ),
        migrations.DeleteModel(
            name='ExamDetail',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='TakeATest',
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.exam'),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupquestionhistory',
            name='practice_part_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.practiceparthistory'),
        ),
        migrations.AddField(
            model_name='exampart',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.exam'),
        ),
    ]
