# Generated by Django 4.1.7 on 2023-03-30 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_auto_20230311_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
