# Generated by Django 4.1.7 on 2023-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_alter_exampart_pass_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
