# Generated by Django 4.1.7 on 2023-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_alter_groupquestion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
