# Generated by Django 4.1.7 on 2023-04-20 01:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0012_alter_question_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='media/default.jpeg', storage=django.core.files.storage.FileSystemStorage(location='/home/holequoctin/Documents/Python/Django/QuizzSystem/media/'), upload_to='media/'),
        ),
    ]
